us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

prop_use_type_lookup = {
'Distribution Center' : 'distributionCenter', 
'Non-Refrigerated Warehouse' : 'nonRefrigeratedWarehouse', 
'Manufacturing/Industrial Plant' : 'manufacturingIndustrialPlant', 
'Mixed Use Property' : 'other', 
'Office' : 'office', 
'Refrigerated Warehouse' : 'refrigeratedWarehouse', 
'Multifamily Housing' : 'multifamilyHousing', 
}

required_prop_uses = {
    'distributionCenter' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'numberOfWalkInRefrigerationUnits', 'clearHeight', 'percentHeated', 'percentCooled'], 
    'office' : ['weeklyOperatingHours', 'numberOfWorkers', 'numberOfComputers', 'percentOfficeCooled', 'percentOfficeHeated'], 
    'nonRefrigeratedWarehouse' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'numberOfWalkInRefrigerationUnits', 'clearHeight', 'percentCooled', 'percentHeated'], 
    'manufacturingIndustrialPlant' : ['weeklyOperatingHours', 'numberOfComputers', 'numberOfWorkers'],
    'other' : ['weeklyOperatingHours', 'numberOfComputers', 'numberOfWorkers'], 
    'refrigeratedWarehouse' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'clearHeight', 'percentCooled', 'percentHeated'],
    'multifamilyHousing' : ['numberOfResidentialLivingUnits', 'numberOfBedrooms', 'numberOfResidentialLivingUnitsMidRiseSetting', 'numberOfLaundryHookupsInAllUnits', 'numberOfLaundryHookupsInCommonArea', 'numberOfResidentialLivingUnitsLowRiseSetting', 'percentHeated', 'percentCooled', 'numberOfResidentialLivingUnitsHighRiseSetting', 'residentPopulation', 'governmentSubsidizedHousing', 'commonEntrance']
}