us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

prop_use_type_lookup = {
    'Distribution Center' : 'distributionCenter', 
    'Non-Refrigerated Warehouse' : 'nonRefrigeratedWarehouse', 
    'Manufacturing/Industrial Plant' : 'manufacturingIndustrialPlant', 
    'Mixed Use Property' : 'other', 
    'Office' : 'office', 
    'Refrigerated Warehouse' : 'refrigeratedWarehouse', 
    'Multifamily Housing' : 'multifamilyHousing', 
    'Repair Services (Vehicle, Shoe, Locksmith, etc)' : 'repairServices'
}

required_prop_uses = {
    'distributionCenter' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'numberOfWalkInRefrigerationUnits', 'clearHeight', 'percentHeated', 'percentCooled'], 
    'office' : ['weeklyOperatingHours', 'numberOfWorkers', 'numberOfComputers', 'percentOfficeCooled', 'percentOfficeHeated'], 
    'nonRefrigeratedWarehouse' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'numberOfWalkInRefrigerationUnits', 'clearHeight', 'percentCooled', 'percentHeated'], 
    'manufacturingIndustrialPlant' : ['weeklyOperatingHours', 'numberOfComputers', 'numberOfWorkers'],
    'other' : ['weeklyOperatingHours', 'numberOfComputers', 'numberOfWorkers'], 
    'refrigeratedWarehouse' : ['weeklyOperatingHours', 'numberOfWorkers', 'percentUsedForColdStorage', 'clearHeight', 'percentCooled', 'percentHeated'],
    'multifamilyHousing' : ['numberOfResidentialLivingUnits', 'numberOfBedrooms', 'numberOfResidentialLivingUnitsMidRiseSetting', 'numberOfLaundryHookupsInAllUnits', 'numberOfLaundryHookupsInCommonArea', 'numberOfResidentialLivingUnitsLowRiseSetting', 'percentHeated', 'percentCooled', 'numberOfResidentialLivingUnitsHighRiseSetting', 'residentPopulation', 'governmentSubsidizedHousing', 'commonEntrance']
}

epa_ids = {
    'Ann Arbor Building ID': '66',
    'Atlanta Building ID': '30',
    'Austin Building ID': '10',
    'Austin Property ID': '9',
    'BOMA BESt Building ID': '22',
    'Berkeley Building ID': '40',
    'Boston Energy Reporting ID': '24',
    'Boulder Energy Reporting ID': '34',
    'British Columbia - Building Benchmark BC ID': '54',
    'California Building ID': '41',
    'Cambridge Building Energy Reporting ID': '26',
    'Chicago Energy Benchmarking ID': '25',
    'Chula Vista Building ID (CVID)': '62',
    'CoStar Property ID': '17',
    'Colorado Building ID': '64',
    'Columbus Building ID': '58',
    'Custom ID 1': '1',
    'Custom ID 2': '2',
    'Custom ID 3': '3',
    'Denver Building ID': '36',
    'Des Moines Building ID': '53',
    'District of Columbia Real Property Unique ID': '6',
    'Evanston Building ID': '38',
    'Fort Collins Building ID': '57',
    'Green Globes CIEB Project ID': '21',
    'Green Globes NC Project ID': '20',
    'HUD Property AMP ID': '39',
    'HUD Property REMS ID': '31',
    'Kansas City Building Reporting ID': '33',
    'LEED Canada Project ID': '19',
    'LEED US Project ID': '18',
    'Longmont CO Energy Benchmarking Building ID': '59',
    'Los Angeles Building ID': '35',
    'Los Angeles County ID': '61',
    'MN Efficient Buildings Collaborative ID': '48',
    'Miami Building ID': '67',
    'Minneapolis Building ID': '14',
    'Minneapolis Property ID': '28',
    'Montgomery County, MD Building ID (MBID)': '27',
    'Montréal - Disclosure Building ID': '63',
    'NYC Borough, Block and Lot (BBL)': '4',
    'NYC Building Identification Number (BIN)': '5',
    'NYC PACE ID': '55',
    'Ontario EWRB ID': '37',
    'Orlando Building ID': '42',
    'Ottawa - Better Buildings ID': '65',
    'Philadelphia Building ID': '8',
    'Pittsburgh Building Benchmarking ID': '43',
    'Portland, ME Building ID': '44',
    'Portland, OR Building ID': '29',
    'REALPac Energy Benchmarking Program Building Name': '23',
    'Reno Building ID': '52',
    'Saint Paul Parcel ID': '47',
    'Salt Lake City Building ID': '49',
    'San Diego Building ID': '50',
    'San Francisco Building ID': '11',
    'San Jose Building ID': '51',
    'Seattle Building Energy Benchmarking Reporting ID': '12',
    'South Portland, ME Energy Reporting ID': '45',
    'St. Louis Building ID': '46',
    'State of Washington Clean Buildings Standard': '60',
    'State of Washington Unique Facilities Identifier (UFI)': '13',
    'US Agency Designated Covered Facility ID': '16',
    'US Federal Real Property Unique Identifier': '15',
    'USDA Property AMAS ID': '32',
    'Unique Building Identifier (UBID)': '56'
 }